### ISSUE TITLE
homopolish then modpolish or just modpolish?

### ISSUE THREAD

**Issue by aldertzomer** [ythuang0522/homopolish#54]
Should modpolish be run instead of homopolish, or after homopolish?

**Comment by ythuang0522** [comment]
Hi @aldertzomer, you should run homopolish first and then modpolish (if you suspect novel modifications). For most cases, homopolish should be sufficient for your needs as it fixes the dominating ONT homopolymer errors (i.e., indels). Modpolish was further developed to correct mismatch/basecalling errors due to novel/unknown modifications, which we spotted in some strains of our bacteria. I hope this helps.

**Comment by aldertzomer** [comment]
This helps a lot, thank you :)
